# Generated by Django 5.0.7 on 2025-03-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otp',
            },
        ),
    ]
