# Generated by Django 5.2 on 2025-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0005_chatsession_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
