# Generated by Django 5.2 on 2025-05-14 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0006_alter_chatsession_options_chatsession_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The name of the variable', max_length=100, unique=True)),
                ('value', models.TextField(help_text='The variable’s value')),
                ('secret', models.BooleanField(default=False, help_text='When True, mask the value in the admin UI')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Automatically updated when this row changes')),
            ],
            options={
                'db_table': 'env_var',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
