# Generated by Django 5.2 on 2025-05-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0007_envvar_alter_chatsession_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envvar',
            name='secret',
        ),
    ]
