# Generated by Django 5.2 on 2025-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0010_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
