# Generated by Django 5.2 on 2025-06-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0013_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='total_session_duration',
            new_name='session_duration',
        ),
    ]
