# Generated by Django 5.2 on 2025-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0016_alter_useractivity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='total_session_duration',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
