# Generated by Django 5.2 on 2025-06-05 04:45

import wowdash_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0017_remove_useractivity_total_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(max_length=100, null=True, blank=True, ),
        ),
    ]
