# Generated by Django 5.2 on 2025-06-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0019_auto_20250605_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
