# Generated by Django 5.2 on 2025-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0020_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_feddback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
