# Generated by Django 5.2 on 2025-06-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0021_chatmessage_message_feddback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message_feddback',
            new_name='message_feedback',
        ),
    ]
