# Generated by Django 5.2 on 2025-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0022_rename_message_feddback_chatmessage_message_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_bot_image', models.ImageField(blank=True, null=True, upload_to='chatbot_pic/')),
            ],
        ),
    ]
