# Generated by Django 5.2 on 2025-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0023_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
