# Generated by Django 5.2 on 2025-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0026_auto_20250606_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='bot_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
