# Generated by Django 5.2 on 2025-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0027_alter_chatsession_bot_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The name of the setting', max_length=100, unique=True)),
                ('value', models.TextField(help_text='The setting’s value')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Automatically updated when this row changes')),
            ],
            options={
                'db_table': 'content_setting',
                'ordering': ['key'],
            },
        ),
    ]
