# Generated by Django 5.2 on 2025-06-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0028_contentsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteImage',
        ),
    ]
