# Generated by Django 5.2 on 2025-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0030_faqcategory_alter_envvar_value_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
