# Generated by Django 5.2 on 2025-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0031_alter_faq_category_alter_faq_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AlterField(
            model_name='contentsetting',
            name='value',
            field=models.TextField(help_text="The setting's value"),
        ),
    ]
