# Generated by Django 5.2 on 2025-06-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0033_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='UserQueries',
        ),
    ]
