# Generated by Django 5.2 on 2025-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0036_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., 1.0.0)', max_length=50)),
                ('release_date', models.DateField()),
                ('heading', models.CharField(max_length=200)),
                ('features', models.JSONField(help_text='Key-value pairs of features and their descriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Release Note',
                'verbose_name_plural': 'Release Notes',
                'ordering': ['-release_date', '-version'],
            },
        ),
    ]
