# Generated by Django 5.2 on 2025-06-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0038_alter_releasenote_features_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user can log in to the website'),
        ),
    ]
