# Generated by Django 5.2 on 2025-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0041_userprofile_department_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
