# Generated by Django 5.2 on 2025-07-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowdash_app', '0043_delete_expense_delete_income_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
